require 'digest/sha1'

class User < ActiveRecord::Base
  
  has_many :bookings
  
  # ---------------------------------------
  # The following code has been generated by role_requirement.
  # You may wish to modify it to suit your need
  has_and_belongs_to_many :roles
  
  # has_role? simply needs to return true or false whether a user has a role or not.  
  # It may be a good idea to have "admin" roles return true always
  def has_role?(role_in_question)
    @_list ||= self.roles.collect(&:name)
    return true if @_list.include?("admin")
    (@_list.include?(role_in_question.to_s) )
  end
  # ---------------------------------------
  
  
  
  
  include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken
  include Authorization::AasmRoles

  validates_presence_of     :login,    :message => "Your Email Address can't be blank."
  validates_length_of       :login,    :within => 6..100
  validates_uniqueness_of   :login,    :message => "Sorry, but that Email Address has already been taken. Please use a different one."
  validates_format_of       :login,    :with => Authentication.email_regex, :message => Authentication.bad_email_message

  validates_presence_of     :first_name,     :message => "Your First Name can't be blank."
  validates_format_of       :first_name,     :with => Authentication.name_regex,  :message => Authentication.bad_name_message
  
  validates_presence_of     :surname,     :message => "Your Surname can't be blank."
  validates_format_of       :surname,     :with => Authentication.name_regex,  :message => Authentication.bad_name_message
  
  validates_presence_of     :phone,     :message => "Your Phone Number can't be blank."

  

  # HACK HACK HACK -- how to do attr_accessible from here?
  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  attr_accessible :login, :email, :first_name, :surname, :phone, :company, :password, :password_confirmation



  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  #
  # uff.  this is really an authorization, not authentication routine.  
  # We really need a Dispatch Chain here or something.
  # This will also let us return a human error message.
  #
  def self.authenticate(login, password)
    return nil if login.blank? || password.blank?
    u = find_in_state :first, :active, :conditions => {:login => login.downcase} # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  def login=(value)
    write_attribute :login, (value ? value.downcase : nil)
  end

  def email=(value)
    write_attribute :email, (value ? value.downcase : nil)
  end

  protected
    
    def make_activation_code
        self.deleted_at = nil
        self.activation_code = self.class.make_token
    end


end
